spring:
  datasource:
    username: sa
    password:
    url: jdbc:hsqldb:file:db/news-bot
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DerbyTenSevenDialect
        ddl-auto: create-drop
